/** SAT Math generators (English, student-produced numeric responses). Every answer is computed. */
type Out = { text: string; ans: number[]; hint: string; ordered?: boolean };
type Rng = { int: (a: number, b: number) => number; pick: <T>(a: T[]) => T };
const mk = (seed: number): Rng => { let a = seed | 0; const r = () => { a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; return { int: (x, y) => Math.floor(r() * (y - x + 1)) + x, pick: (arr) => arr[Math.floor(r() * arr.length)] }; };
const sg = (n: number) => (n < 0 ? `- ${-n}` : `+ ${n}`);
const r2 = (n: number) => Math.round(n * 100) / 100;

export const SAT_TOPICS = [
  { code: "SAT.MATH.ALGEBRA", name: "Algebra" }, { code: "SAT.MATH.ADVANCED", name: "Advanced Math" },
  { code: "SAT.MATH.PROBLEM_SOLVING", name: "Problem-Solving and Data Analysis" }, { code: "SAT.MATH.GEOMETRY_TRIG", name: "Geometry and Trigonometry" },
];

export const SAT: Record<string, { topic: string; title: string; build: (r: Rng) => Out }> = {
  "sat-linear-eq": { topic: "SAT.MATH.ALGEBRA", title: "Linear equations", build: (r) => { const x = r.int(-9, 12), a = r.int(2, 9), b = r.int(1, 20), c = r.int(2, 6); const d = a * x + b - c * x; if (a === c) return SAT["sat-linear-eq"].build(r); return { text: `If $${a}x + ${b} = ${c}x ${sg(d)}$, what is the value of $x$?`, ans: [x], hint: `Collect like terms: $${a - c}x = ${d - b}$, so $x = ${x}$.` }; } },
  "sat-linear-expr": { topic: "SAT.MATH.ALGEBRA", title: "Value of an expression", build: (r) => { const x = r.int(2, 12), a = r.int(2, 7), k = r.int(2, 5); return { text: `If $${a}x = ${a * x}$, what is the value of $${a * k}x - ${k}$?`, ans: [a * k * x - k], hint: `$x = ${x}$, so $${a * k}\\cdot ${x} - ${k} = ${a * k * x - k}$.` }; } },
  "sat-system": { topic: "SAT.MATH.ALGEBRA", title: "Systems of linear equations", build: (r) => { const x = r.int(-5, 8), y = r.int(-5, 8), a = r.int(1, 4), b = r.int(1, 4), c = r.int(1, 4); return { text: `$${a}x + ${b}y = ${a * x + b * y}$\n\n$${c}x - ${b}y = ${c * x - b * y}$\n\nThe solution to the system is $(x, y)$. What is the value of $x + y$?`, ans: [x + y], hint: `Add the equations: $${a + c}x = ${(a + c) * x}$, so $x = ${x}$ and $y = ${y}$.` }; } },
  "sat-slope": { topic: "SAT.MATH.ALGEBRA", title: "Slope of a line", build: (r) => { const m = r.pick([-3, -2, -1, 2, 3, 4, 0.5, 1.5]), x1 = r.int(-4, 4), y1 = r.int(-6, 6), dx = r.pick([2, 4, 6]); return { text: `Line $\\ell$ passes through the points $(${x1}, ${y1})$ and $(${x1 + dx}, ${y1 + m * dx})$ in the $xy$-plane. What is the slope of line $\\ell$?`, ans: [m], hint: `Slope $= \\frac{${y1 + m * dx} - (${y1})}{${x1 + dx} - (${x1})} = ${m}$.` }; } },
  "sat-linear-context": { topic: "SAT.MATH.ALGEBRA", title: "Linear models in context", build: (r) => { const fee = r.int(15, 60), rate = r.int(4, 18), h = r.int(3, 9); const who = r.pick(["A plumber", "A tutor", "An electrician", "A bike shop"]); return { text: `${who} charges a fixed fee of $\\$${fee}$ plus $\\$${rate}$ per hour. If the total charge was $\\$${fee + rate * h}$, how many hours were billed?`, ans: [h], hint: `$${fee} + ${rate}h = ${fee + rate * h}$, so $h = ${h}$.` }; } },
  "sat-inequality": { topic: "SAT.MATH.ALGEBRA", title: "Linear inequalities", build: (r) => { const a = r.int(2, 7), b = r.int(1, 15), c = r.int(10, 60); const bound = (c - b) / a; const ans = Number.isInteger(bound) ? bound - 1 : Math.floor(bound); return { text: `What is the greatest integer $x$ that satisfies $${a}x + ${b} < ${c}$?`, ans: [ans], hint: `$x < ${r2(bound)}$, so the greatest integer is $${ans}$.` }; } },
  "sat-quadratic": { topic: "SAT.MATH.ADVANCED", title: "Quadratic equations", build: (r) => { let p = r.int(-7, 8), q = r.int(-7, 8); if (p === q) q = p + 3; return { text: `What is the sum of the solutions to $x^2 ${sg(-(p + q))}x ${sg(p * q)} = 0$?`, ans: [p + q], hint: `The solutions are $${p}$ and $${q}$; by Vieta the sum is $${p + q}$.` }; } },
  "sat-quadratic-pos": { topic: "SAT.MATH.ADVANCED", title: "Positive solution of a quadratic", build: (r) => { const p = r.int(1, 9), q = -r.int(1, 9); return { text: `What is the positive solution to $x^2 ${sg(-(p + q))}x ${sg(p * q)} = 0$?`, ans: [p], hint: `Factor: $(x - ${p})(x + ${-q}) = 0$; the positive solution is $${p}$.` }; } },
  "sat-vertex": { topic: "SAT.MATH.ADVANCED", title: "Vertex of a parabola", build: (r) => { const h = r.int(-5, 6), k = r.int(-9, 9), a = r.pick([1, 2, 3]); const b = -2 * a * h, c = a * h * h + k; return { text: `The function $f$ is defined by $f(x) = ${a === 1 ? "" : a}x^2 ${sg(b)}x ${sg(c)}$. What is the minimum value of $f$?`, ans: [k], hint: `Vertex at $x = ${h}$: $f(${h}) = ${k}$.` }; } },
  "sat-exponential": { topic: "SAT.MATH.ADVANCED", title: "Exponential growth", build: (r) => { const p0 = r.pick([100, 200, 500, 1000]), f = r.pick([2, 3]), n = r.int(2, 4); return { text: `A population of bacteria is modeled by $P(t) = ${p0}\\cdot ${f}^{t}$, where $t$ is the number of hours. What is $P(${n})$?`, ans: [p0 * f ** n], hint: `$${p0}\\cdot ${f}^{${n}} = ${p0 * f ** n}$.` }; } },
  "sat-function-value": { topic: "SAT.MATH.ADVANCED", title: "Function notation", build: (r) => { const a = r.int(2, 5), b = r.int(-8, 8), x = r.int(-4, 5); return { text: `If $f(x) = ${a}x^2 ${sg(b)}$, what is the value of $f(${x})$?`, ans: [a * x * x + b], hint: `$${a}(${x})^2 ${sg(b)} = ${a * x * x + b}$.` }; } },
  "sat-radical-eq": { topic: "SAT.MATH.ADVANCED", title: "Radical equations", build: (r) => { const s = r.int(2, 9), b = r.int(1, 20); return { text: `If $\\sqrt{x + ${b}} = ${s}$, what is the value of $x$?`, ans: [s * s - b], hint: `Square both sides: $x + ${b} = ${s * s}$.` }; } },
  "sat-percent": { topic: "SAT.MATH.PROBLEM_SOLVING", title: "Percent", build: (r) => { const p = r.pick([10, 15, 20, 25, 30, 40]), price = r.pick([40, 60, 80, 120, 200, 240]); return { text: `A jacket originally priced at $\\$${price}$ is on sale for $${p}\\%$ off. What is the sale price, in dollars?`, ans: [price * (1 - p / 100)], hint: `$${price}\\cdot ${r2(1 - p / 100)} = ${price * (1 - p / 100)}$.` }; } },
  "sat-ratio": { topic: "SAT.MATH.PROBLEM_SOLVING", title: "Ratios and rates", build: (r) => { const a = r.int(2, 5), b = r.int(3, 7), k = r.int(3, 9); return { text: `The ratio of red to blue marbles in a bag is $${a}:${b}$. If there are $${(a + b) * k}$ marbles in total, how many are blue?`, ans: [b * k], hint: `Each part is $${(a + b) * k} \\div ${a + b} = ${k}$; blue $= ${b}\\cdot ${k}$.` }; } },
  "sat-unit-rate": { topic: "SAT.MATH.PROBLEM_SOLVING", title: "Unit rates", build: (r) => { const v = r.pick([45, 50, 55, 60, 65]), t = r.pick([1.5, 2, 2.5, 3, 4]); return { text: `A car travels at a constant speed of $${v}$ miles per hour. How many miles does it travel in $${t}$ hours?`, ans: [v * t], hint: `$${v}\\cdot ${t} = ${v * t}$.` }; } },
  "sat-mean": { topic: "SAT.MATH.PROBLEM_SOLVING", title: "Mean of a data set", build: (r) => { const n = 5, mean = r.int(10, 30); const xs = Array.from({ length: n - 1 }, () => r.int(mean - 8, mean + 8)); const last = mean * n - xs.reduce((s, v) => s + v, 0); return { text: `The mean of five numbers is $${mean}$. Four of the numbers are $${xs.join(", ")}$. What is the fifth number?`, ans: [last], hint: `Total must be $${mean * n}$; $${mean * n} - ${xs.reduce((s, v) => s + v, 0)} = ${last}$.` }; } },
  "sat-probability": { topic: "SAT.MATH.PROBLEM_SOLVING", title: "Probability", build: (r) => { const a = r.int(2, 9), b = r.int(2, 9), c = r.int(2, 9); return { text: `A box contains $${a}$ red, $${b}$ green and $${c}$ yellow tokens. One token is chosen at random. What is the probability that it is NOT green? (Enter a fraction or a decimal.)`, ans: [(a + c) / (a + b + c)], hint: `$\\frac{${a + c}}{${a + b + c}}$.` }; } },
  "sat-triangle-area": { topic: "SAT.MATH.GEOMETRY_TRIG", title: "Area", build: (r) => { const b = r.int(4, 20), h = r.int(3, 14); return { text: `A triangle has a base of $${b}$ and a height of $${h}$. What is its area?`, ans: [(b * h) / 2], hint: `$\\frac{1}{2}\\cdot ${b}\\cdot ${h} = ${(b * h) / 2}$.` }; } },
  "sat-pythagorean": { topic: "SAT.MATH.GEOMETRY_TRIG", title: "Right triangles", build: (r) => { const [a, b, c] = r.pick([[3, 4, 5], [5, 12, 13], [8, 15, 17], [7, 24, 25]]).map((v) => v * r.int(1, 3)); return { text: `In a right triangle, the legs have lengths $${a}$ and $${b}$. What is the length of the hypotenuse?`, ans: [Math.sqrt(a * a + b * b)], hint: `$\\sqrt{${a}^2 + ${b}^2} = \\sqrt{${a * a + b * b}} = ${c}$.` }; } },
  "sat-angles": { topic: "SAT.MATH.GEOMETRY_TRIG", title: "Angles in a triangle", build: (r) => { const a = r.int(25, 80), b = r.int(25, 70); return { text: `Two angles of a triangle measure $${a}^\\circ$ and $${b}^\\circ$. What is the measure, in degrees, of the third angle?`, ans: [180 - a - b], hint: `$180 - ${a} - ${b} = ${180 - a - b}$.` }; } },
  "sat-circle": { topic: "SAT.MATH.GEOMETRY_TRIG", title: "Circle equations", build: (r) => { const h = r.int(-6, 6), k = r.int(-6, 6), rad = r.int(2, 9); return { text: `A circle in the $xy$-plane has equation $(x ${sg(-h)})^2 + (y ${sg(-k)})^2 = ${rad * rad}$. What is the radius of the circle?`, ans: [rad], hint: `$r^2 = ${rad * rad}$, so $r = ${rad}$.` }; } },
  "sat-trig": { topic: "SAT.MATH.GEOMETRY_TRIG", title: "Right-triangle trigonometry", build: (r) => { const [a, b, c] = r.pick([[3, 4, 5], [5, 12, 13], [8, 15, 17]]); return { text: `In right triangle $ABC$, angle $C$ is the right angle, $BC = ${a}$, $AC = ${b}$ and $AB = ${c}$. What is the value of $\\sin A$? (Enter a fraction or a decimal.)`, ans: [a / c], hint: `$\\sin A = \\frac{\\text{opposite}}{\\text{hypotenuse}} = \\frac{${a}}{${c}}$.` }; } },
};
export const buildSat = (id: string, seed: number): Out => SAT[id].build(mk(seed));
